language: python
python: 3.3
env:
  matrix:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34

install:
  - pip install tox
  - pip install coveralls
  - pip install -r requirements.txt -r requirements-dev.txt

script:
  tox

after_success:
  coveralls
