language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'

install:
  - pip install -r requirements.txt -r requirements-dev.txt

script:
  - python setup.py clean
  - python setup.py build
  - coverage run --source=pykakasi setup.py test

after_success:
  - coveralls
  - python setup.py sdist
  - python setup.py bdist_wheel --plat-name manylinux1_i686
  - python setup.py bdist_wheel --plat-name manylinux1_x86_64

deploy:
  - provider: pypi
    user: miurahr
    password:
      secure: CUY3E7DJMMyC9ARkkC5plAWTAnwmp+wyS+GbRgjOPDL8H4AwzCSCD03D4z/5BHHpGFilF+sAsaNte/9dDjtzEXtvmMCfJwovShnr9GdAm+PU4+TyhEWqVYbeYHiJMiSnLPcsyJMkYZ8JtNMXyp0onPQr6P28OsEq+ohG6Ha9P1Y=
    distributions: sdist bdist_wheel
    skip_existing: true
    on:
      repo: miurahr/pykakasi
      python: '3.6'
      tags: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f32fb3bc2d3933f7926f
    on_success: change
    on_failure: always
    on_start: never
