install:
  - "python.exe -m pip install -U -r requirements-dev.txt -r requirements.txt"

build_script: 
  - "python.exe setup.py build"

test_script:
  - "python.exe setup.py test"

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/527beafbc6f6f66bf889
    method: POST
