environment:
  matrix:
    - PYTHON: "C:\\Python36"

install:
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install -U -r requirements-dev.txt -r requirements.txt"

build_script: 
  - "%PYTHON%\\python.exe setup.py build"

test_script:
  - "%PYTHON%\\python.exe setup.py test"

after_test:
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/527beafbc6f6f66bf889
    method: POST
