environment:
  PYPI_USERNAME: miurahr
  PYPI_PASSWORD:
    secure: ibyxU09f3mAdoh5Hv4T27Q==
  PYTHON: "C:\\Python36"

install:
  - "%PYTHON%\\python.exe -m pip install twine wheel"
  - "%PYTHON%\\python.exe -m pip install -U -r requirements-dev.txt -r requirements.txt"

build_script: 
  - "%PYTHON%\\python.exe setup.py build"

test_script:
  - "%PYTHON%\\python.exe setup.py test"

after_test:
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*

deploy_script:
  - ps: If ($env:APPVEYOR_REPO_TAG -eq "true") {Invoke-Expression "twine upload --skip-existing dist/*" 2>$null}

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/527beafbc6f6f66bf889
    method: POST
